name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Linting
        run: npm run lint

  prettier:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Prettier Check
        run: npm run prettier:check

  unit_test:
    runs-on: ubuntu-latest
    needs: prettier
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless

  code_analysis:
    runs-on: ubuntu-latest
    needs: unit_test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Code Analysis
        run: npm run test:ci

  # e2e_test:
  #   runs-on: ubuntu-latest
  #   needs: code_analysis
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '20'

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Start the application
  #       run: npm run start -- --port 4201 --watch=false & # Start the application on a different port

  #     - name: Run End-to-End Tests
  #       run: npm run e2e -- --watch=false

  Build:
    runs-on: ubuntu-latest
    needs: e2e_test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Notify completion
        run: echo "Cheers Danilo!!!!"
      - name: List directory contents
        run: ls -la

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build --prod

      - name: Create zip file
        run: zip -r Danilo.zip ./dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Danilo
          path: Danilo.zip
