name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Updated Node.js version to 20

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

  prettier:
    runs-on: ubuntu-latest
    needs: lint # This job will run after the lint job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Updated Node.js version to 20

      - name: Install dependencies
        run: npm install

      - name: Check formatting with Prettier
        run: npm run prettier:check

  unit-test:
    runs-on: ubuntu-latest
    needs: prettier # This job will run after the prettier job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Updated Node.js version to 20

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless --code-coverage

  code-analysis:
    runs-on: ubuntu-latest
    needs: unit-test # This job will run after the unit-test job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Updated Node.js version to 20

      - name: Install dependencies
        run: npm install

      - name: Run code analysis
        run: npm run test:ci # Assuming this script runs lint and tests together

  e2e_test:
    runs-on: ubuntu-latest
    needs: code-analysis
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run End-to-End Tests
        run: npm run e2e -- --watch=false

  build:
    runs-on: ubuntu-latest
    needs: e2e_test # This job will run after the e2e_test job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Updated Node.js version to 20

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Create ZIP of build artifacts
        run: |
          zip -r build-artifact.zip ./dist # Create a ZIP file of the build output

      - name: Upload build artifact
        uses: actions/upload-artifact@v3 # Updated to v3
        with:
          name: build-artifact
          path: build-artifact.zip # Upload the ZIP file

      - name: Echo Name
        run: echo "Build artifact created by Danilo Pelaso Jr"
